name: 02 - workflow events
on: [push, pull_request, schedule, workflow_dispatch]
jobs:
    first-job:
        name: echo
        runs-on: ubuntu-latest
        steps:
           -  name: show the trigger
              run: echo ${{ github.event_name }}