name: 04 - Using Actions
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
              working-directory: react-manual/react-app
            - name: Unit Tests
              run: npm run test
              working-directory: react-manual/react-app

              
