name: "01 - Building Blocks"
on: [workflow_dispatch]

jobs:
  first_job:
    name: echo-hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
  second_job:
    name: echo-goodbye
    runs-on: ubuntu-latest
    steps:
      - name: failed step
        run: |
          echo "I will fail"
          exit 1
      - name: Say Goodbye
        run: echo "Goodbye!" 
